version: '2'

services:
  web001:
    image: porchn/php5.6.28-apache
    container_name: web001
    volumes:
      - ./apache2/conf:/etc/apache2/sites-enabled
      - ./apache2/www:/var/www
      - ./apache2/logs:/var/log/apache2
    environment:
      - TZ=Asia/Bangkok
    restart: always
    networks:
      - webnetwork

  web002:
    image: porchn/php5.6.28-apache
    container_name: web002
    volumes:
      - ./apache2/conf:/etc/apache2/sites-enabled
      - ./apache2/www:/var/www
      - ./apache2/logs:/var/log/apache2
    environment:
      - TZ=Asia/Bangkok
    restart: always
    networks:
      - webnetwork

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - data-cache:/data-cache
    environment:
      - TZ=Asia/Bangkok
      - NGINX_PORT=80
    restart: always
    links: 
      - web001:web001
      - web002:web002
    networks:
      - webnetwork
      
volumes:
  data-cache:
    driver: local

networks:
  webnetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.20.0.0/16
          ip_range: 10.20.5.0/24
          gateway: 10.20.5.254

